[project]
name = "lg-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "bhl-arunpujari", email = "arun.pujari@basichomeloan.com" }
]
requires-python = ">=3.12"
dependencies = [
    "langchain-tavily>=0.2.18",
]

[project.scripts]
langgraph = "langgraph:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false
